spring:
  application:
    name: day1

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true

  ai:
    openai:
      # 키는 소스에 넣지 않는다.  export OPENAI_API_KEY="sk-..."
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none
    display-request-duration: true

logging:
  level:
    skala.springai.day1: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics" # 또는 "*" 로 전체 노출
  endpoint:
    metrics:
      enabled: true